version: 1.0.{build}
build_script:
- cmd: dotnet build
test_script:
- cmd: dotnet test --no-restore
artifacts:
- path: ./DomainRepository.EventStore/bin/Release/*.nupkg
  name: Nuget
deploy_script:
- cmd: dotnet pack  -c Release /p:PackageVersion=1.0.{build}