os: Visual Studio 2017
version: 1.0.{build}
branches:
  only:
    - master
configuration:
- Release
before_build:
- dotnet restore
build:
  project: DomainRepository.EventStore.sln
after_build:
- ps: >-
    $BuildVersion = (Get-ChildItem Env:APPVEYOR_BUILD_VERSION).value

    dotnet pack DomainRepository.EventStore/DomainRepository.EventStore.csproj -c Release /p:Version=$BuildVersion

artifacts:
  - path: DomainRepository.EventStore\bin\Release\netstandard1.6\DomainRepository.EventStore.dll
    name: DomainRepository.EventStore.dll
  - path: DomainRepository.EventStore\bin\Release\*.nupkg

deploy:
    provider: NuGet
    server: https://www.nuget.org/
    api_key:
        secure: aB7bp5vsAMf8vnHtADyDX0Vq0Ef5AkZnw+rlK2yhqz+Nh+xZBh0NYZOa/qeoQLRn